Update unit-tests.yml

diff --git a/.github/workflows/unit-tests.yml b/.github/workflows/unit-tests.yml
--- a/.github/workflows/unit-tests.yml
+++ b/.github/workflows/unit-tests.yml
@@ -31,7 +31,7 @@ jobs:
                 node: ['14']
 
         steps:
-            - uses: actions/checkout@v3
+            - uses: actions/checkout@v2
 
             - name: Setup Node.js and install dependencies
               uses: ./.github/setup-node
@@ -43,6 +43,42 @@ jobs:
 
             - name: Running the tests
               run: npm run test:js
+    test-php:
+        name: PHP
+        runs-on: ubuntu-latest
+        timeout-minutes: 20
+        if: ${{ github.repository == 'publisherwp/publisher-core' || github.event_name == 'pull_request' }}
+
+        steps:
+            - uses: actions/checkout@v2
+
+            - name: Setup Node.js and install dependencies
+              uses: ./.github/setup-node
+
+            - name: Running unit tests
+              run: |
+                  set -o pipefail
+                  npm run test:unit:php | tee phpunit.log
+
+            # Verifies that PHPUnit actually runs in the first place. We want visibility
+            # into issues which can cause it to fail silently, so we check the output
+            # to verify that at least 500 tests have passed. This is an arbitrary
+            # number, but makes sure a drastic change doesn't happen without us noticing.
+            - name: Check number of passed tests
+              run: |
+                  # Note: relies on PHPUnit execution to fail on test failure.
+                  # Extract the number of executed tests from the log file.
+                  if ! num_tests=$(grep -Eo 'OK \([0-9]+ tests' phpunit.log) ; then
+                    if ! num_tests=$(grep -Eo 'Tests: [0-9]+, Assertions:' phpunit.log) ; then
+                      echo "PHPUnit failed or did not run. Check the PHPUnit output in the previous step to debug." && exit 1
+                    fi
+                  fi
+                  # Extract just the number of tests from the string.
+                  num_tests=$(echo "$num_tests" | grep -Eo '[0-9]+')
+                  if [ $num_tests -lt 500 ] ; then
+                    echo "Only $num_tests tests passed, which is much fewer than expected." && exit 1
+                  fi
+                  echo "$num_tests tests passed."
 
     phpcs:
         name: PHP coding standards
@@ -68,7 +104,7 @@ jobs:
               run: echo "date=$(/bin/date -u --date='last Mon' "+%F")" >> $GITHUB_OUTPUT
 
             - name: Cache PHPCS scan cache
-              uses: actions/cache@88522ab9f39a2ea568f7027eddc7d8d8bc9d59c8 # v3.3.1
+              uses: actions/cache@v3
               with:
                   path: .cache/phpcs.json
                   key: ${{ runner.os }}-date-${{ steps.get-date.outputs.date }}-phpcs-cache-${{ hashFiles('**/composer.json', 'phpcs.xml.dist') }}
@@ -93,22 +129,3 @@ jobs:
 
             - name: Ensure version-controlled files are not modified during the tests
               run: git diff --exit-code
-
-    # This job is deprecated but be present for compatibility reasons.
-    unit-php:
-        name: PHP
-        runs-on: ubuntu-latest
-        needs: [test-php, phpcs]
-        if: ${{ always() }}
-        steps:
-            - name: Fail the job if the PHPUnit tests fail
-              if: ${{ needs.test-php.result != 'success' }}
-              run: exit 1
-
-            - name: "Fail the job if the code doesn't conform to the coding standards"
-              if: ${{ needs.phpcs.result != 'success' }}
-              run: exit 1
-
-            - name: Mark the job as passed if all the checks pass
-              if: ${{ needs.test-php.result == 'success' && needs.phpcs.result == 'success' }}
-              run: exit 0
